# PHP project
language: php

# which versions of PHP to build with
php:
- 7.0

# set global environment variables
env:
  global:
    # make PROJECTNAME from vendor/project
    # this strips everything before the last /
    - PROJECTNAME=${TRAVIS_REPO_SLUG##*/}

# make sure we have the latest version of composer
before_install:
- composer self-update

# install dependencies
install:
- composer install

# no phpunit tests (yet)
script: true

# no email notifications
notifications:
  email: false

# before deployment make the zipfile to upload
before_deploy:
 # execute release prepare script
 - sh ./vendor/coldtrick/releases/scripts/travis/before_deploy.sh

# deployment settings
deploy:
  provider: releases
  api_key:
    secure: DFtBdb8wfvgx+TYG9d2C4wq/E1fyC1hxPHV14HJKLUEXBlO+qztNYylp7/1tK+HARwgtW1Sia/j37ISu1l1vBu/ofikRa1YLWFu7jQ/zZ6cJ5b9TuDINkVrjJMGrywQ4E/9/ZnjFUgLUKQTVFA8gEMceT/Yc4IQONHbMtNi+akgiiASGn43d1FUvjs3nnNY/wgrRv32sfmYRlZoiI/trvbcJkPg6ADl5pdiK0tgR+k3dbdsTt5Gji4rRFL9aoc+s/wyXVxWkemEoHvY+sxpwonKZ934GvVguHG79V/kmLNZRapW6TTAmveWHHW/Azes1exVQUDbuuSMhYWQLpSKQqmweoRy4twiC4nzbcRSZ9zg9F/LKkkWH7Bq6GtqBOj83aMp7v73GGKz5aFL24PrHcjBHC4zAiJW05aRFgHxIkVmJPOBu12+NvXPjAvmxAIInc4nZFxBNTy+2k2EciJacly+90ZgemVHlUf0mhCKLX2b/Yq4rq5CbnwvSWbH4XgzIMwXv9H/5R7y+SwMm8qhfAw/Vwv8cxdHI3cPUN7+/BaRSXBlovjcrXJMo00lwHgNBpeqB2zUj2cRYPypJ4w+PL+IYpBa6nmnTsU+BtYb1z1P0mtDJu5leXgQNZZZcqSP4wuM8SV1LHj9Rek9HOebNNyFOC28aomRKSgNX8MsZcmM=
  # name of the zip to upload
  file: ${PROJECTNAME}_$TRAVIS_TAG.zip
  skip_cleanup: true
  on:
    # only when a tag is created in GitHub
    tags: true
    all_branches: true

after_deploy:
 # execute release after script
 - sh ./vendor/coldtrick/releases/scripts/travis/after_deploy.sh
